# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backwork', '0001_initial'),
        ('cutcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PishSab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slids', models.IntegerField()),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backwork.timebackwork')),
            ],
            options={
                'verbose_name': 'پیش ساب',
                'verbose_name_plural': 'پیش ساب',
            },
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCUPE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pishsab.pishsab')),
                ('Numslab', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cutcode.size')),
            ],
            options={
                'verbose_name': 'سنگ برگشتی',
                'verbose_name_plural': 'سنگ برگشتی',
            },
        ),
    ]
