# Generated by Django 4.2.20 on 2025-06-25 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0026_alter_materialfrontwork_bakiye_active'),
        ('pishsab', '0003_pishsab_elferam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PishSabReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('SlabNumber', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerfactory.regects', to_field='numslab')),
            ],
            options={
                'verbose_name': 'سنگ برگشتی',
                'verbose_name_plural': 'سنگ برگشتی',
            },
        ),
        migrations.DeleteModel(
            name='Reject',
        ),
    ]
