# Generated by Django 4.2.20 on 2025-06-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0026_alter_materialfrontwork_bakiye_active'),
        ('pishsab', '0005_alter_pishsabreject_slabnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishsabreject',
            name='SlabNumber',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerfactory.regects', to_field='numslab'),
        ),
    ]
