# Generated by Django 4.2.20 on 2025-06-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0009_alter_backworkreject_slabnumber'),
        ('pishsab', '0009_alter_pishsab_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishsab',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backwork.timebackwork'),
        ),
    ]
