# Generated by Django 4.2.20 on 2025-06-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
        ('backwork', '0010_alter_backworkreject_slabnumber'),
        ('pishsab', '0011_alter_pishsab_idcupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='fk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fild_one', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerfactory.regects', to_field='numslab')),
                ('fild_two', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backwork.backworkreject', to_field='SlabNumber')),
            ],
        ),
        migrations.AlterField(
            model_name='pishsabreject',
            name='SlabNumber',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pishsab.fk'),
        ),
    ]
