# Generated by Django 4.2.20 on 2025-06-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0010_alter_backworkreject_slabnumber'),
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
        ('pishsab', '0012_fk_alter_pishsabreject_slabnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pishsabreject',
            name='SlabNumber',
        ),
        migrations.AddField(
            model_name='pishsabreject',
            name='backwork_reject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pishsab_reject', to='backwork.backworkreject'),
        ),
        migrations.AddField(
            model_name='pishsabreject',
            name='slab_number',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='pishsab_rejects', to='managerfactory.regects', to_field='numslab'),
        ),
        migrations.DeleteModel(
            name='fk',
        ),
    ]
