# Generated by Django 4.2.20 on 2025-06-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
        ('pishsab', '0013_remove_pishsabreject_slabnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pishsabreject',
            name='backwork_reject',
        ),
        migrations.RemoveField(
            model_name='pishsabreject',
            name='slab_number',
        ),
        migrations.AddField(
            model_name='pishsabreject',
            name='SlabNumber',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.regects', to_field='numslab'),
        ),
    ]
