# Generated by Django 4.2.20 on 2025-06-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0010_alter_backworkreject_slabnumber'),
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
        ('pishsab', '0014_remove_pishsabreject_backwork_reject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conect_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backwork.backworkreject')),
                ('conect_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.regects')),
            ],
        ),
        migrations.AlterField(
            model_name='pishsabreject',
            name='SlabNumber',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pishsab.conect'),
        ),
    ]
