# Generated by Django 4.2.20 on 2025-06-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
        ('pishsab', '0016_alter_conect_conect_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishsabreject',
            name='SlabNumber',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.regects', to_field='numslab'),
        ),
        migrations.DeleteModel(
            name='Conect',
        ),
    ]
