# Generated by Django 4.2.20 on 2025-06-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0010_alter_backworkreject_slabnumber'),
        ('pishsab', '0017_alter_pishsabreject_slabnumber_delete_conect'),
    ]

    operations = [
        migrations.AddField(
            model_name='pishsabreject',
            name='Resicetobackwork',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backwork.backworkreject'),
        ),
    ]
