# Generated by Django 4.2.20 on 2025-06-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontwork', '0007_alter_frontworkreject_resicetobackwork'),
        ('pishsab', '0018_pishsabreject_resicetobackwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishsabreject',
            name='Resicetobackwork',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontwork.frontworkreject'),
        ),
    ]
