"""
Django settings for nosaz project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)#6lcq9_)@_zu%-=&&d&q7^4b+--+6ywb!7^#i2dvluz!af^!x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

    

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',  # برای احراز هویت توکن
    'rest_framework',
    'django_jalali',
    'corsheaders',
    'cupeinter',
    'cut',
    'cutcode',
    'backwork',
    'storage',
    'vacium',
    'Furnace',
    'sellmanager',
    'pishsab',
    'sab',
    'managerfactory',
    'frontwork',
    'users',
    'ferez',
    # 'data',
]


LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
USE_L10N = True
USE_TZ = True
import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/frontend')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# برای تولید
ALLOWED_HOSTS = ['*']

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # خیلی مهم
]



CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # برای توسعه React
]
AUTH_USER_MODEL = 'users.Profile'  # به جای users نام اپ خود را قرار دهید


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]
CORS_ALLOW_ALL_ORIGINS = True  # فقط برای تست


REST_FRAMEWORK = {'DEFAULT_RENDERER_CLASSES':['rest_framework.permission.AllowAny','rest_framework_simplejwt.authentication.JWTAuthentication']}


CORS_ORIGIN_ALLOW_ALL = True


ROOT_URLCONF = 'nosaz.urls'
TEMPLATES = [
    {
        'DIRS': [os.path.join(BASE_DIR, 'static/frontend')],
    },
]

WSGI_APPLICATION = 'nosaz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}