# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.vaciummaterialstorage')),
            ],
            options={
                'verbose_name': 'وکیوم',
                'verbose_name_plural': 'وکیوم',
            },
        ),
    ]
