# Generated by Django 4.2.20 on 2025-06-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_alter_vaciummaterialstorage_material'),
        ('vacium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacium',
            name='material',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.vaciummaterialstorage', to_field='material'),
        ),
    ]
