# Generated by Django 4.2.20 on 2025-06-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_alter_vaciummaterialstorage_material'),
        ('vacium', '0008_alter_vacium_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacium',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.vaciummaterialstorage', unique=True),
        ),
    ]
