# Generated by Django 4.2.20 on 2025-06-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0026_alter_frontworkmatrialstorage_material'),
        ('frontwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontwork',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.frontworkmatrialstorage', to_field='material_id'),
        ),
    ]
