# Generated by Django 4.2.20 on 2025-06-24 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0025_alter_regects_numslab'),
        ('frontwork', '0003_frontwork_elferam'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontWorkReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('SlabNumber', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerfactory.regects', to_field='numslab')),
            ],
        ),
    ]
