# Generated by Django 4.2.20 on 2025-06-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0010_alter_backworkreject_slabnumber'),
        ('frontwork', '0005_alter_frontworkreject_slabnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontworkreject',
            name='Resicetobackwork',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backwork.backworkreject'),
        ),
    ]
