# Generated by Django 4.2.20 on 2025-06-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pishsab', '0018_pishsabreject_resicetobackwork'),
        ('frontwork', '0006_frontworkreject_resicetobackwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontworkreject',
            name='Resicetobackwork',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pishsab.pishsabreject'),
        ),
    ]
