# Generated by Django 4.2.20 on 2025-06-24 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sab', '0003_sab_elferam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('NumbersSlabsFerez', models.IntegerField()),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sab.sab', to_field='IDCUPE_id')),
            ],
        ),
        migrations.CreateModel(
            name='SizeFerez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumbersCutFerez', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('Elferam', models.IntegerField()),
                ('CUT_ID', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferez.ferez')),
            ],
        ),
    ]
