# Generated by Django 4.2.20 on 2025-06-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeferez',
            name='CUT_ID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferez.ferez'),
        ),
    ]
