# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopeInter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCUPE', models.IntegerField()),
                ('NameStone', models.CharField(max_length=120)),
                ('CupeType', models.CharField(max_length=120)),
                ('CupeHeight', models.CharField(max_length=120)),
                ('CupeWeight', models.CharField(max_length=120)),
                ('CupeWidth', models.CharField(max_length=120)),
                ('CupeOwner', models.CharField(max_length=120)),
                ('CarThreeNumber', models.IntegerField()),
                ('CarAlfabet', models.CharField(max_length=120)),
                ('CarTwoNumber', models.IntegerField()),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'کات',
                'verbose_name_plural': 'کات',
            },
        ),
    ]
