# Generated by Django 4.2.20 on 2025-06-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupeinter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copeinter',
            name='IDCUPE',
            field=models.IntegerField(unique=True),
        ),
    ]
