# Generated by Django 4.2.20 on 2025-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupeinter', '0002_alter_copeinter_idcupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='copeinter',
            name='CupeLength',
            field=models.CharField(default='', max_length=120),
        ),
    ]
