# Generated by Django 4.2.20 on 2025-08-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupeinter', '0003_copeinter_cupelength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copeinter',
            name='DataTime',
        ),
    ]
