# Generated by Django 4.2.20 on 2025-08-01 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cupeinter', '0004_remove_copeinter_datatime'),
    ]

    operations = [
        migrations.AddField(
            model_name='copeinter',
            name='DataTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
