# Generated by Django 4.2.20 on 2025-08-01 17:00

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cupeinter', '0005_copeinter_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copeinter',
            name='DataTime',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
