# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cut', '0001_initial'),
        ('Furnace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnace',
            name='IDCUPE',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cut.cut'),
        ),
    ]
