# Generated by Django 4.2.20 on 2025-06-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0010_alter_cut_idcupe'),
        ('Furnace', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnace',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cut.cut', to_field='IDCUPE_id'),
        ),
    ]
