# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupeinter', '0001_initial'),
        ('pishsab', '0001_initial'),
        ('cut', '0001_initial'),
        ('cutcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegectToBackAndFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrontWork', models.BooleanField()),
                ('BackWork', models.BooleanField()),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cut.cut')),
            ],
            options={
                'verbose_name': 'سنگ های برگشتی',
                'verbose_name_plural': 'سنگ های برگشتی',
            },
        ),
        migrations.CreateModel(
            name='ProductionStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cupeinter.copeinter')),
            ],
            options={
                'verbose_name': 'انتخاب کوپ',
                'verbose_name_plural': 'انتخاب کوپ',
            },
        ),
        migrations.CreateModel(
            name='MaterialFrontWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epocsi_active', models.BooleanField(default=False, verbose_name='فعال بودن اپوکسی')),
                ('zhel_active', models.BooleanField(default=False, verbose_name='فعال بودن ژل')),
                ('mastic_active', models.BooleanField(default=False, verbose_name='فعال بودن ماستیک')),
                ('rezin_active', models.BooleanField(default=False, verbose_name='فعال بودن رزین')),
                ('bakiye_active', models.BooleanField(default=False, verbose_name='فعال بودن باقی مانده')),
                ('tori_active', models.BooleanField(default=False, verbose_name='فعال بودن توری')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cut_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pishsab.pishsab', verbose_name='کد برش')),
            ],
            options={
                'verbose_name': ' ماده اولیه گاری رو',
                'verbose_name_plural': ' ماده اولیه گاری رو',
            },
        ),
        migrations.CreateModel(
            name='MaterialBackWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epocsi_active', models.BooleanField(verbose_name='فعال بودن اپوکسی')),
                ('zhel_active', models.BooleanField(verbose_name='فعال بودن ژل')),
                ('mastic_active', models.BooleanField(verbose_name='فعال بودن ماستیک')),
                ('rezin_active', models.BooleanField(verbose_name='فعال بودن رزین')),
                ('bakiye_active', models.BooleanField(verbose_name='فعال بودن باقی مانده')),
                ('tori_active', models.BooleanField(verbose_name='فعال بودن توری')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cut_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutcode.cutcode', verbose_name='کد برش')),
            ],
            options={
                'verbose_name': ' ماده اولیه گاری پشت',
                'verbose_name_plural': ' ماده اولیه گاری پشت',
            },
        ),
        migrations.CreateModel(
            name='Makesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacium', models.BooleanField(default=False)),
                ('Boghche', models.BooleanField(default=False)),
                ('DontUse', models.BooleanField(default=False)),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cupeinter.copeinter')),
            ],
            options={
                'verbose_name': 'مواد اولیه وکیوم',
                'verbose_name_plural': 'مواد اولیه وکیوم',
            },
        ),
    ]
