# Generated by Django 4.2.20 on 2025-06-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutcode', '0001_initial'),
        ('managerfactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbackwork',
            options={'verbose_name': ' ماده اولیه گاری رو', 'verbose_name_plural': ' ماده اولیه گاری رو'},
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='bakiye_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن باقی مانده'),
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='cut_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cutcode.cutcode', verbose_name='کد برش'),
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='epocsi_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن اپوکسی'),
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='mastic_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ماستیک'),
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='rezin_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن رزین'),
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='tori_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن توری'),
        ),
        migrations.AlterField(
            model_name='materialbackwork',
            name='zhel_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ژل'),
        ),
    ]
