# Generated by Django 4.2.20 on 2025-06-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0002_alter_materialbackwork_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbackwork',
            options={'verbose_name': ' ماده اولیه گاری پشت', 'verbose_name_plural': ' ماده اولیه گاری پشت'},
        ),
    ]
