# Generated by Django 4.2.20 on 2025-06-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupeinter', '0002_alter_copeinter_idcupe'),
        ('managerfactory', '0007_alter_productionstone_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makesh',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cupeinter.copeinter', to_field='IDCUPE'),
        ),
    ]
