# Generated by Django 4.2.20 on 2025-06-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0014_alter_makesh_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makesh',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.productionstone'),
        ),
    ]
