# Generated by Django 4.2.20 on 2025-06-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutcode', '0002_alter_cutcode_idcupe'),
        ('managerfactory', '0016_alter_makesh_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbackwork',
            name='cut_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cutcode.cutcode', to_field='IDCUPE_id', verbose_name='کد برش'),
        ),
    ]
