# Generated by Django 4.2.20 on 2025-06-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pishsab', '0002_alter_pishsab_idcupe'),
        ('managerfactory', '0017_alter_materialbackwork_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfrontwork',
            name='cut_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pishsab.pishsab', to_field='IDCUPE_id', verbose_name='کد برش'),
        ),
    ]
