# Generated by Django 4.2.20 on 2025-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0018_alter_materialfrontwork_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbackwork',
            name='epocsi_active',
            field=models.BooleanField(verbose_name='فعال بودن اپوکسی'),
        ),
    ]
