# Generated by Django 4.2.20 on 2025-06-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0004_backworkreject'),
        ('managerfactory', '0019_alter_materialbackwork_epocsi_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='backrejects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCUPE', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back_rejects', to='backwork.backworkreject', to_field='IDCUPE_id')),
            ],
        ),
        migrations.CreateModel(
            name='Regects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='RegectToBackAndFront',
        ),
    ]
