# Generated by Django 4.2.20 on 2025-06-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0005_alter_backworkreject_slabnumber'),
        ('managerfactory', '0020_backrejects_regects_delete_regecttobackandfront'),
    ]

    operations = [
        migrations.AddField(
            model_name='backrejects',
            name='numslab',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to='backwork.backworkreject', to_field='SlabNumber'),
        ),
    ]
