# Generated by Django 4.2.20 on 2025-06-24 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0005_alter_backworkreject_slabnumber'),
        ('managerfactory', '0021_backrejects_numslab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToRejects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackWorkToReject', models.BooleanField(default=False)),
                ('FrontWorkToReject', models.BooleanField(default=False)),
                ('PishSabReject', models.BooleanField(default=False)),
                ('SabReject', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='regects',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_rejects', to='backwork.backworkreject', to_field='IDCUPE_id'),
        ),
        migrations.AddField(
            model_name='regects',
            name='numslab',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejects', to='backwork.backworkreject', to_field='SlabNumber'),
        ),
        migrations.DeleteModel(
            name='backrejects',
        ),
        migrations.AddField(
            model_name='torejects',
            name='Regects_Code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.regects'),
        ),
    ]
