# Generated by Django 4.2.20 on 2025-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0022_torejects_regects_idcupe_regects_numslab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regects',
            name='BackWorkToReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regects',
            name='FrontWorkToReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regects',
            name='PishSabReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regects',
            name='SabReject',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ToRejects',
        ),
    ]
