# Generated by Django 4.2.20 on 2025-06-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutcode', '0003_alter_size_cut_code'),
        ('managerfactory', '0023_regects_backworktoreject_regects_frontworktoreject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regects',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_rejects', to='cutcode.cutcode', to_field='IDCUPE_id'),
        ),
        migrations.AlterField(
            model_name='regects',
            name='numslab',
            field=models.IntegerField(verbose_name='num_slab'),
        ),
    ]
