# Generated by Django 4.2.20 on 2025-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0024_alter_regects_idcupe_alter_regects_numslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regects',
            name='numslab',
            field=models.IntegerField(default=False, unique=True, verbose_name='num_slab'),
        ),
    ]
