# Generated by Django 4.2.20 on 2025-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0025_alter_regects_numslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfrontwork',
            name='bakiye_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن بخیه'),
        ),
    ]
