# Generated by Django 4.2.20 on 2025-06-25 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0026_alter_materialfrontwork_bakiye_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='regects',
            name='DataTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
