# Generated by Django 4.2.20 on 2025-06-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pishsab', '0011_alter_pishsab_idcupe'),
        ('managerfactory', '0033_alter_materialfrontwork_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfrontwork',
            name='cut_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IDCUPE_id', to='pishsab.pishsab', verbose_name='کد برش'),
        ),
    ]
