# Generated by Django 4.2.20 on 2025-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0035_alter_materialfrontwork_cut_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regects',
            name='IDCUPE',
        ),
        migrations.AlterField(
            model_name='regects',
            name='numslab',
            field=models.IntegerField(unique=True, verbose_name='شماره اسلب'),
        ),
    ]
