# Generated by Django 4.2.20 on 2025-07-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makesh',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.productionstone', to_field='IDCUPE_id'),
        ),
    ]
