services:
  - type: web
    name: nosazapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nosaz.nosaz.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nosaz.settings
