# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumbersCut', models.IntegerField()),
                ('CutNote', models.TextField(default=None)),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'کات',
                'verbose_name_plural': 'کات',
            },
        ),
    ]
