# Generated by Django 4.2.20 on 2025-06-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacium', '0012_alter_vacium_material'),
        ('cut', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='IDCUPE',
        ),
        migrations.AddField(
            model_name='cut',
            name='id_CUPE',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacium.vacium'),
        ),
    ]
