# Generated by Django 4.2.20 on 2025-06-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0003_remove_cut_idcupe_cut_id_cupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='id_CUPE',
            new_name='IDCUPE',
        ),
    ]
