# Generated by Django 4.2.20 on 2025-06-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacium', '0012_alter_vacium_material'),
        ('cut', '0005_alter_cut_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='IDCUPE',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='vacium.vacium'),
        ),
    ]
