# Generated by Django 4.2.20 on 2025-06-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacium', '0012_alter_vacium_material'),
        ('cut', '0008_rename_id_cupe_cut_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='IDCUPE',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacium.vacium', to_field='material'),
        ),
    ]
