# Generated by Django 4.2.20 on 2025-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0011_alter_cut_idcupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='Elferam',
            field=models.IntegerField(default=False),
        ),
    ]
