# Generated by Django 4.2.20 on 2025-06-20 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Furnace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteCutCode', models.TextField(default=False)),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Furnace.furnace')),
            ],
            options={
                'verbose_name': 'کدگذاری',
                'verbose_name_plural': 'کدگذاری',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeihtCutCode', models.IntegerField()),
                ('WidthCutCode', models.IntegerField()),
                ('ThicknessCutCode', models.IntegerField()),
                ('NumsCutCod', models.IntegerField(default=False)),
                ('cut_code', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutcode.cutcode')),
            ],
        ),
    ]
