# Generated by Django 4.2.20 on 2025-06-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Furnace', '0003_alter_furnace_idcupe'),
        ('cutcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutcode',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Furnace.furnace', to_field='IDCUPE_id'),
        ),
    ]
