# Generated by Django 4.2.20 on 2025-06-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutcode', '0018_alter_size_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='cut_code',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cutcode.cutcode', to_field='IDCUPE_id'),
        ),
    ]
