# Generated by Django 4.2.20 on 2025-06-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutcode', '0029_alter_size_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='cut_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cutcode.cutcode', to_field='IDCUPE_id'),
        ),
    ]
