# Generated by Django 4.2.20 on 2025-07-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Furnace', '0003_alter_furnace_idcupe'),
        ('cutcode', '0031_alter_size_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutcode',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Furnace.furnace'),
        ),
    ]
