# Generated by Django 4.2.20 on 2025-06-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_alter_backworkmatrialstorage_material'),
        ('backwork', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebackwork',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.backworkmatrialstorage', to_field='material_id'),
        ),
    ]
