# Generated by Django 4.2.20 on 2025-06-23 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_alter_backworkmatrialstorage_epocsi'),
        ('backwork', '0003_alter_timebackwork_idcupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackWorkReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlabNumber', models.IntegerField()),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('IDCUPE', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.backworkmatrialstorage', to_field='material_id')),
            ],
        ),
    ]
