# Generated by Django 4.2.20 on 2025-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0004_backworkreject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkreject',
            name='SlabNumber',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
