# Generated by Django 4.2.20 on 2025-06-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0005_alter_backworkreject_slabnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backworkreject',
            name='SlabNumber',
        ),
    ]
