# Generated by Django 4.2.20 on 2025-06-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backwork', '0007_backworkreject_slabnumber_timebackwork_elferam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backworkreject',
            name='IDCUPE',
        ),
    ]
