# Generated by Django 4.2.20 on 2025-06-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0025_alter_regects_numslab'),
        ('backwork', '0008_remove_backworkreject_idcupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkreject',
            name='SlabNumber',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerfactory.regects', to_field='numslab'),
        ),
    ]
