# Generated by Django 4.2.20 on 2025-06-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0036_remove_regects_idcupe_alter_regects_numslab'),
        ('backwork', '0009_alter_backworkreject_slabnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkreject',
            name='SlabNumber',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerfactory.regects', to_field='numslab'),
        ),
    ]
