# Generated by Django 4.2.20 on 2025-06-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontwork', '0002_alter_frontwork_idcupe'),
        ('sab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sab',
            name='IDCUPE',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontwork.frontwork', to_field='IDCUPE_id'),
        ),
    ]
