# Generated by Django 4.2.20 on 2025-06-27 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontwork', '0007_alter_frontworkreject_resicetobackwork'),
        ('sab', '0003_sab_elferam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResicetoSab', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sab_rejects', to='frontwork.frontworkreject')),
                ('SlabNumber', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sab.sab')),
            ],
            options={
                'verbose_name': 'سنگ برگشتی',
                'verbose_name_plural': 'سنگ برگشتی',
            },
        ),
        migrations.DeleteModel(
            name='Reject',
        ),
    ]
