# Generated by Django 4.2.20 on 2025-06-27 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sab', '0004_sabreject_delete_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabreject',
            name='DataTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
