# Generated by Django 4.2.20 on 2025-06-20 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managerfactory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaciumMaterialStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelastic', models.IntegerField()),
                ('tori', models.IntegerField()),
                ('lole', models.IntegerField()),
                ('chasbe123', models.IntegerField()),
                ('chasbekaghazi', models.IntegerField()),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vacium', to='managerfactory.makesh')),
            ],
            options={
                'verbose_name': 'مواد وکیوم',
                'verbose_name_plural': 'مواد وکیوم',
            },
        ),
        migrations.CreateModel(
            name='FrontWorkMatrialStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epocsi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='اپوکسی')),
                ('zhel', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ژل')),
                ('mastic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ماستیک')),
                ('rezin', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='رزین')),
                ('bakiye', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='باقی مانده')),
                ('tori', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='توری')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_works', to='managerfactory.materialfrontwork', verbose_name=' ماده اولیه')),
            ],
            options={
                'verbose_name': 'مواد گاری رو ',
                'verbose_name_plural': 'مواد گاری رو ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BackWorkMatrialStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epocsi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='اپوکسی')),
                ('zhel', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ژل')),
                ('mastic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ماستیک')),
                ('rezin', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='رزین')),
                ('bakiye', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='باقی مانده')),
                ('tori', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='توری')),
                ('DataTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_works', to='managerfactory.materialbackwork', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'مواد گاری پشت ',
                'verbose_name_plural': 'مواد گاری پشت',
                'ordering': ['-id'],
            },
        ),
    ]
