# Generated by Django 4.2.20 on 2025-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='bakiye',
            field=models.IntegerField(blank=True, null=True, verbose_name='باقی مانده'),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(blank=True, null=True, verbose_name='اپوکسی'),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='mastic',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماستیک'),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='rezin',
            field=models.IntegerField(blank=True, null=True, verbose_name='رزین'),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='tori',
            field=models.IntegerField(blank=True, null=True, verbose_name='توری'),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='zhel',
            field=models.IntegerField(blank=True, null=True, verbose_name='ژل'),
        ),
    ]
