# Generated by Django 4.2.20 on 2025-06-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0003_alter_materialbackwork_options'),
        ('storage', '0003_alter_backworkmatrialstorage_bakiye_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backworkmatrialstorage',
            options={'verbose_name': 'مواد گاری پشت ', 'verbose_name_plural': 'مواد گاری پشت'},
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerfactory.materialbackwork'),
        ),
    ]
