# Generated by Django 4.2.20 on 2025-06-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0003_alter_materialbackwork_options'),
        ('storage', '0004_alter_backworkmatrialstorage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_work_material', to='managerfactory.materialbackwork'),
        ),
    ]
