# Generated by Django 4.2.20 on 2025-06-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0003_alter_materialbackwork_options'),
        ('storage', '0005_alter_backworkmatrialstorage_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontworkmatrialstorage',
            options={'verbose_name': 'مواد گاری رو ', 'verbose_name_plural': 'مواد گاری رو '},
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='bakiye',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='mastic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_work_material', to='managerfactory.materialbackwork'),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='rezin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='tori',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='zhel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='bakiye',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='mastic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_works', to='managerfactory.materialfrontwork'),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='rezin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='tori',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='zhel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='chasbe123',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='chasbekaghazi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='lole',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='pelastic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='tori',
            field=models.IntegerField(null=True),
        ),
    ]
