# Generated by Django 4.2.20 on 2025-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_frontworkmatrialstorage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaciummaterialstorage',
            old_name='chasbekaghazi',
            new_name='chasbedotarafe',
        ),
        migrations.RenameField(
            model_name='vaciummaterialstorage',
            old_name='lole',
            new_name='chasbeghiri',
        ),
        migrations.RenameField(
            model_name='vaciummaterialstorage',
            old_name='tori',
            new_name='epocsivacium',
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='lolerodei',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='lolevacium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='mayea123',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='rezin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='tori400',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='toridocupe',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='torivacium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vaciummaterialstorage',
            name='zhelvacium',
            field=models.IntegerField(null=True),
        ),
    ]
