# Generated by Django 4.2.20 on 2025-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_rename_chasbekaghazi_vaciummaterialstorage_chasbedotarafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='bakiye',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='mastic',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='rezin',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='tori',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='zhel',
            field=models.IntegerField(default=False),
        ),
    ]
