# Generated by Django 4.2.20 on 2025-06-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0008_alter_makesh_idcupe'),
        ('storage', '0013_alter_vaciummaterialstorage_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='material',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vacium', to='managerfactory.makesh', to_field='IDCUPE'),
        ),
    ]
