# Generated by Django 4.2.20 on 2025-06-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0012_alter_makesh_idcupe'),
        ('storage', '0019_alter_vaciummaterialstorage_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back_works', to='managerfactory.materialfrontwork'),
        ),
    ]
