# Generated by Django 4.2.20 on 2025-06-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0017_alter_materialbackwork_cut_code'),
        ('storage', '0023_alter_vaciummaterialstorage_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='material',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_work_material', to='managerfactory.materialbackwork', to_field='cut_code'),
        ),
    ]
