# Generated by Django 4.2.20 on 2025-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0027_alter_frontworkmatrialstorage_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='chasbe123',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='chasbedotarafe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='chasbeghiri',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='epocsivacium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='lolerodei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='lolevacium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='mayea123',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='pelastic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='rezin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='tori400',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='toridocupe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='torivacium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaciummaterialstorage',
            name='zhelvacium',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
