# Generated by Django 4.2.20 on 2025-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0028_alter_vaciummaterialstorage_chasbe123_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(),
        ),
    ]
