# Generated by Django 4.2.20 on 2025-06-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0025_alter_regects_numslab'),
        ('storage', '0029_alter_backworkmatrialstorage_epocsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back_works', to='managerfactory.materialfrontwork', to_field='cut_code'),
        ),
    ]
