# Generated by Django 4.2.20 on 2025-06-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerfactory', '0025_alter_regects_numslab'),
        ('storage', '0031_alter_frontworkmatrialstorage_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backwork_storage', to='managerfactory.materialbackwork', to_field='cut_code', verbose_name='ماده بازکاری'),
        ),
    ]
