# Generated by Django 4.2.20 on 2025-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0032_alter_backworkmatrialstorage_epocsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='bakiye',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='mastic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='rezin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='tori',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='backworkmatrialstorage',
            name='zhel',
            field=models.IntegerField(),
        ),
    ]
