# Generated by Django 4.2.20 on 2025-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0038_alter_vaciummaterialstorage_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='bakiye',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='epocsi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='mastic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='rezin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='tori',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontworkmatrialstorage',
            name='zhel',
            field=models.IntegerField(default=0),
        ),
    ]
